### ISSUE TITLE
Figure out a CI solution

### ISSUE THREAD

**Issue by rkrzewski** [rkrzewski/akka-cluster-etcd#18]
Requirements:
- Free for OSS projects
- Github checks integration to allow PR validation process
- Docker support: we need to spawn two containers sharing a network interface: one with etcd and another with sbt running project tests

**Comment by rkrzewski** [comment]
https://www.cloudbees.com/resources/foss is one option to consider.
http://documentation.cloudbees.com/docs/cje-user-guide/pull-request-builder-for-github.html
http://documentation.cloudbees.com/docs/cje-user-guide/docker-workflow.html

**Comment by maciej** [comment]
What about [TravisCI](https://travis-ci.org)? Doesn't it meet the requirements?

**Comment by rkrzewski** [comment]
Can you spawn arbitrary Docker containers from TravisCI build? I thought it was rather focused / limited WRT tools you can use.

**Comment by maciej** [comment]
http://docs.travis-ci.com/user/docker/ – we might want to explore this. I'm not sure if this is available for FOSS projects, though.

**Comment by rkrzewski** [comment]
https://travis-ci.com/plans <-- yes it is

**Comment by maciej** [comment]
It'd try out Travis first, then. It seems to me to be the most common choice among FOSS projects.

**Comment by rkrzewski** [comment]
:+1:
