### ISSUE TITLE
Update to Akka streams / HTTP 2.0 when released

### ISSUE THREAD

**Issue by rkrzewski** [rkrzewski/akka-cluster-etcd#22]
There are API changes coming up, so it may turn out a non-trivial task.

**Comment by maciej** [comment]
@rkrzewski that's interesting. The Akka team promised to have the API stabilised by 1.0. Do you have any links to any material on those changes?

**Comment by rkrzewski** [comment]
https://github.com/akka/akka/pull/18700 + some other refactorings currently in progress.
It's called an _experimental_ module for a reason ;)

**Comment by ktoso** [comment]
"More stable" yes, it certainly is now. 
The changes in 1.1 are renames, not much structural changes (and we won't do any more structural changes).
As mentioned, we may indeed change APIs in streams, they're still experimental for that reason :)

We'll write a migration guide so it won't be hard to update, a few search/replace in an IDE should be enough :)

**Comment by rkrzewski** [comment]
Good to know :) Thanks!

**Comment by maciej** [comment]
@rkrzewski are you thinking of moving to Akka Streams 2.0 already or do you want to wait for the final version? I could rewrite the `FlowBreaker` (#33) to be `GraphStage`-based once you move. :-)

**Comment by rkrzewski** [comment]
I was just about to write a comment on this subject in #33, but then I've noticed the notification :)
I'd rather move now, 2.0-M2 seems to be pretty solid, and hopefully most compatibility breaking changes are already in.
It will be next item on my list, now that demo application is done.

**Comment by maciej** [comment]
@rkrzewski I'm all for moving to Akka Streams 2.0-M2. I've already written a handful o `GraphStage`s, so I'll gladly write another one that accepts async notifications. ;-)

**Comment by ktoso** [comment]
Thanks guys! Yeah, moving to 2.0 early (Milestones) would be very nice, since perhaps you'll have some feedback about the news APIs :-)

// Please remember that milestones are "development snapshot" and M3 may not be binary compatible with M2.

**Comment by maciej** [comment]
@ktoso definitely! BTW I'm working with 2.0 streams all days long recently, so if anything – I'll be dropping any spotted bugs or improvements ideas whenever they come up

**Comment by ktoso** [comment]
Great, please do – thanks in advance!

**Comment by rkrzewski** [comment]
Done, we're on 2.0-M2 now.

I'm leaving the issue open for future upgrades to 2.0 milestones.

**Comment by rkrzewski** [comment]
Strange ... Travis build is failing [#39](https://travis-ci.org/rkrzewski/akka-cluster-etcd/builds/95087523)

```
[warn]  [NOT FOUND  ] com.typesafe.akka#akka-stream-testkit-experimental_2.11;2.0-M2!akka-stream-testkit-experimental_2.11.jar (0ms)
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/typesafe/akka/akka-stream-testkit-experimental_2.11/2.0-M2/akka-stream-testkit-experimental_2.11-2.0-M2.jar
```

https://jcenter.bintray.com/com/typesafe/akka/akka-stream-testkit-experimental_2.11/2.0-M2/ contains contains javadocs, sources & POM but not the binaries jar itself. @ktoso could you take a look? 

My local Ivy cache contains that jar and I most definitely haven't built it locally - sbt had to download it from _somewhere_...

**Comment by ktoso** [comment]
Why does it even hit bintray? Akka is always released to maven central directly: http://repo1.maven.org/maven2/com/typesafe/akka/akka-stream-experimental_2.11/2.0-M2/

**Comment by ktoso** [comment]
We'll have a look at the bintray issue though, thanks for reporting!

**Comment by maciej** [comment]
I remember having this issue some [time ago](https://github.com/erikvanoosten/metrics-scala/issues/67) with Travis with another artefact. For some reason they are not using Maven Central.

**Comment by rkrzewski** [comment]
Probably relevant to Travis / JCenter issue: https://github.com/sbt/sbt/issues/2217

However, running `show fullResolvers` only shows `public: https://repo1.maven.org/maven2/` remote repo. I have no idea why (and how) would Travis override the default resolvers used by SBT...

**Comment by rkrzewski** [comment]
I've added separate issue #40 to track Travis / JCenter problem

**Comment by ktoso** [comment]
Thanks!
