### ISSUE TITLE
ActorSystem in `EitherJunctionSpec` is not terminated

### ISSUE THREAD

**Issue by maciej** [rkrzewski/akka-cluster-etcd#32]
ActorSystem in `EitherJunctionSpec` is not terminated.

To be honest, I don't know whether `ActorSystem`s resources are finalised after when it's GCed. A quick Google search did not provide an answer for this question. @rkrzewski do you know the answer? :-)
[Akka documentation](http://doc.akka.io/docs/akka/snapshot/scala/testing.html#Asynchronous_Integration_Testing_with_TestKit) recommends shutting down the system in tests in `afterAll` block.

Resource (think: threads) leakage is a problem when running tests interactively in SBT.

**Comment by rkrzewski** [comment]
`EitherJunction` and it's tests were removed in #7, but I found that `EtcdClientSpec` was not terminating it's `ActorSystem`. I've fixed that in ffe51563 and checked using `jstack` that there are no lingering dispatcher threads after running tests in sbt.
