### ISSUE TITLE
Travis builds failing due to dependencies missing from jcenter.bintray.com

### ISSUE THREAD

**Issue by rkrzewski** [rkrzewski/akka-cluster-etcd#40]
[Build #43](https://travis-ci.org/rkrzewski/akka-cluster-etcd/builds/95168323)

```
[warn]  [NOT FOUND  ] com.typesafe.akka#akka-stream-testkit-experimental_2.11;2.0-M2!akka-stream-testkit-experimental_2.11.jar (0ms)
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/typesafe/akka/akka-stream-testkit-experimental_2.11/2.0-M2/akka-stream-testkit-experimental_2.11-2.0-M2.jar
```

The file is actually missing from bintray but:
- it is available in Maven Central where Akka releases are actually published
- sbt build configuration for this project does not alter default resolvers which do not include bintray at all 

Probably related issue reported against sbt: https://github.com/sbt/sbt/issues/2217

**Comment by rkrzewski** [comment]
Upstream issue: https://github.com/akka/akka/issues/19096

**Comment by rkuhn** [comment]
Can you remove jcenter.bintray.com from your maven configuration? That (together with clearing the local cache) should be a valid workaround.

**Comment by rkrzewski** [comment]
I'm using sbt 0.13.9 to build the project and jcenter.bintray.com is not
referenced anywhere in my project's build files.

The problem occurs on Travis CI, not on my local machine.

Do you mean that Travis CI has some default Maven configuration I need to
override?

**Comment by rkuhn** [comment]
I don't know Travis CI but there should be some configuration for artifact resolvers. OTOH jfrog are looking into this issue as well.

**Comment by rkrzewski** [comment]
The missing jar showed up on jcenter.bintray.org, but I still have no idea why sbt running on Travis CI is hitting it. Even with `resolvers -= Resolver.jcenterRepo` at the top of `build.sbt` I see the folowing in the logs:

```
[info] downloading https://jcenter.bintray.com/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-library;2.11.7!scala-library.jar (2045ms)
```
