### ISSUE TITLE
change ⇒ to =>

### ISSUE THREAD

**Issue by mingchuno** [rkrzewski/akka-cluster-etcd#49]
I saw `⇒` is all around in the source code. Although it is ok to use `⇒` instead of `=>`, I think it is better to use `=>` instead as it is ASCII char. I can submit a PR for the changes if @rkrzewski  agree.

**Comment by rkrzewski** [comment]
Usage of Unicode operators is intentional. I prefer to keep it that way.

**Comment by mingchuno** [comment]
Just curious. May I ask why it is intentional?

**Comment by rkrzewski** [comment]
I became accustomed to this convention while studying Akka sources. In fact, I like it so much that I contributed a patch to Scalariform to convert -> into → https://github.com/daniel-trinh/scalariform/issues/34 :smile:
